-- MySQL Script generated by MySQL Workbench
-- dom 24 nov 2019 23:30:43 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema CampeonadodeFutebol
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `CampeonadodeFutebol` ;

-- -----------------------------------------------------
-- Schema CampeonadodeFutebol
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CampeonadodeFutebol` ;
USE `CampeonadodeFutebol` ;

-- -----------------------------------------------------
-- Table `CampeonadodeFutebol`.`campeonato`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CampeonadodeFutebol`.`campeonato` ;

CREATE TABLE IF NOT EXISTS `CampeonadodeFutebol`.`campeonato` (
  `codCampeonato` INT(11) NOT NULL AUTO_INCREMENT,
  `inicio` DATE NULL DEFAULT NULL,
  `fim` DATE NULL DEFAULT NULL,
  `timeVencedor` INT(11) NULL DEFAULT NULL,
  `artilheiro` INT(11) NULL DEFAULT NULL,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`codCampeonato`),
  INDEX `fk_campeonato_timeVencedor` (`timeVencedor` ASC),
  INDEX `fk_campeonato` (`artilheiro` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `CampeonadodeFutebol`.`cartao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CampeonadodeFutebol`.`cartao` ;

CREATE TABLE IF NOT EXISTS `CampeonadodeFutebol`.`cartao` (
  `tempoDaPartida` DATE NOT NULL,
  `partida_codPartida` INT(11) NOT NULL,
  `jogador_codJogador` INT(11) NOT NULL,
  INDEX `fk_cartao_jogador1_idx` (`jogador_codJogador` ASC),
  PRIMARY KEY (`tempoDaPartida`, `partida_codPartida`, `jogador_codJogador`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `CampeonadodeFutebol`.`clube`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CampeonadodeFutebol`.`clube` ;

CREATE TABLE IF NOT EXISTS `CampeonadodeFutebol`.`clube` (
  `CNPJ` FLOAT NOT NULL,
  `estadioSede` VARCHAR(30) NULL DEFAULT NULL,
  `nome` VARCHAR(30) NULL DEFAULT NULL,
  PRIMARY KEY (`CNPJ`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `CampeonadodeFutebol`.`clube_casa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CampeonadodeFutebol`.`clube_casa` ;

CREATE TABLE IF NOT EXISTS `CampeonadodeFutebol`.`clube_casa` (
  `clube_CNPJ` FLOAT NOT NULL,
  INDEX `fk_clube_visitante_clube1_idx` (`clube_CNPJ` ASC),
  PRIMARY KEY (`clube_CNPJ`),
  CONSTRAINT `fk_clube_visitante_clube10`
    FOREIGN KEY (`clube_CNPJ`)
    REFERENCES `CampeonadodeFutebol`.`clube` (`CNPJ`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CampeonadodeFutebol`.`clube_visitante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CampeonadodeFutebol`.`clube_visitante` ;

CREATE TABLE IF NOT EXISTS `CampeonadodeFutebol`.`clube_visitante` (
  `clube_CNPJ` FLOAT NOT NULL,
  INDEX `fk_clube_visitante_clube1_idx` (`clube_CNPJ` ASC),
  PRIMARY KEY (`clube_CNPJ`),
  CONSTRAINT `fk_clube_visitante_clube1`
    FOREIGN KEY (`clube_CNPJ`)
    REFERENCES `CampeonadodeFutebol`.`clube` (`CNPJ`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CampeonadodeFutebol`.`contrato`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CampeonadodeFutebol`.`contrato` ;

CREATE TABLE IF NOT EXISTS `CampeonadodeFutebol`.`contrato` (
  `codContrato` INT(11) NOT NULL AUTO_INCREMENT,
  `inicio` DATE NULL DEFAULT NULL,
  `fim` DATE NULL DEFAULT NULL,
  `clube_CNPJ` FLOAT NOT NULL,
  `jogador_codJogador` INT(11) NOT NULL,
  PRIMARY KEY (`codContrato`, `jogador_codJogador`, `clube_CNPJ`),
  INDEX `fk_contrato_clube1_idx` (`clube_CNPJ` ASC),
  INDEX `fk_contrato_jogador1_idx` (`jogador_codJogador` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `CampeonadodeFutebol`.`estadio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CampeonadodeFutebol`.`estadio` ;

CREATE TABLE IF NOT EXISTS `CampeonadodeFutebol`.`estadio` (
  `codEstadio` INT(11) NOT NULL AUTO_INCREMENT,
  `cidade` VARCHAR(30) NULL DEFAULT NULL,
  `capacidadeMax` VARCHAR(30) NULL DEFAULT NULL,
  `nome` VARCHAR(30) NULL DEFAULT NULL,
  PRIMARY KEY (`codEstadio`))
ENGINE = MyISAM
AUTO_INCREMENT = 19
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `CampeonadodeFutebol`.`gol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CampeonadodeFutebol`.`gol` ;

CREATE TABLE IF NOT EXISTS `CampeonadodeFutebol`.`gol` (
  `tempoDaPartida` DATE NOT NULL,
  `partida_codPartida` INT(11) NOT NULL,
  `jogador_codJogador` INT(11) NOT NULL,
  PRIMARY KEY (`partida_codPartida`, `tempoDaPartida`, `jogador_codJogador`),
  INDEX `fk_gol_jogador1_idx` (`jogador_codJogador` ASC),
  CONSTRAINT `fk_gol_partida1`
    FOREIGN KEY (`partida_codPartida`)
    REFERENCES `CampeonadodeFutebol`.`partida` (`codPartida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gol_jogador1`
    FOREIGN KEY (`jogador_codJogador`)
    REFERENCES `CampeonadodeFutebol`.`jogador` (`codJogador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `CampeonadodeFutebol`.`jogador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CampeonadodeFutebol`.`jogador` ;

CREATE TABLE IF NOT EXISTS `CampeonadodeFutebol`.`jogador` (
  `codJogador` INT(11) NOT NULL AUTO_INCREMENT,
  `posicao` VARCHAR(30) NULL DEFAULT NULL,
  `primeiroNome` VARCHAR(30) NULL DEFAULT NULL,
  `sobrenome` VARCHAR(30) NULL DEFAULT NULL,
  `altura` FLOAT NULL DEFAULT NULL,
  `peso` FLOAT NULL DEFAULT NULL,
  `dataDeascimento` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`codJogador`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `CampeonadodeFutebol`.`partida`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CampeonadodeFutebol`.`partida` ;

CREATE TABLE IF NOT EXISTS `CampeonadodeFutebol`.`partida` (
  `codPartida` INT(11) NOT NULL AUTO_INCREMENT,
  `dataDaPartida` DATE NULL DEFAULT NULL,
  `estadio_codEstadio` INT(11) NOT NULL,
  `clube_visitante_clube_CNPJ` FLOAT NOT NULL,
  `clube_casa_clube_CNPJ` FLOAT NOT NULL,
  PRIMARY KEY (`codPartida`, `clube_visitante_clube_CNPJ`, `clube_casa_clube_CNPJ`),
  INDEX `fk_partida_estadio1_idx` (`estadio_codEstadio` ASC),
  INDEX `fk_partida_clube_visitante1_idx` (`clube_visitante_clube_CNPJ` ASC),
  INDEX `fk_partida_clube_casa1_idx` (`clube_casa_clube_CNPJ` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `CampeonadodeFutebol`.`registro_campeonato`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CampeonadodeFutebol`.`registro_campeonato` ;

CREATE TABLE IF NOT EXISTS `CampeonadodeFutebol`.`registro_campeonato` (
  `clube_CNPJ` FLOAT NOT NULL,
  `campeonato_codCampeonato` INT(11) NOT NULL,
  `anoCampeonato` DATE NULL,
  `num_registroCampeonato` INT NOT NULL,
  `registro_campeonatocol` VARCHAR(45) NULL,
  INDEX `fk_clube_has_campeonato_campeonato1_idx` (`campeonato_codCampeonato` ASC),
  INDEX `fk_clube_has_campeonato_clube_idx` (`clube_CNPJ` ASC),
  PRIMARY KEY (`num_registroCampeonato`, `clube_CNPJ`, `campeonato_codCampeonato`),
  CONSTRAINT `fk_clube_has_campeonato_clube`
    FOREIGN KEY (`clube_CNPJ`)
    REFERENCES `CampeonadodeFutebol`.`clube` (`CNPJ`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_clube_has_campeonato_campeonato1`
    FOREIGN KEY (`campeonato_codCampeonato`)
    REFERENCES `CampeonadodeFutebol`.`campeonato` (`codCampeonato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
